site_name: Ramais CDA NATAL
nav:
  - Inicio: list/ramal-list.md
  
theme:
  name: material

  palette:

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top

markdown_extensions:
  - codehilite
  - admonition
  - def_list
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true     
  - attr_list
  - md_in_html

extra_css:
  - css/extra.css

extra_javascript:
  - javascripts/tablesort.js

